CREATE TABLE IF NOT EXISTS "TotalesBanco" (
	"num_cambios" integer DEFAULT 0,
	"fmaxdes1" numeric(8, 2) DEFAULT '0'::numeric,
	"fmaxdes2" numeric(8, 2) DEFAULT '0'::numeric,
	"fmaxdes3" numeric(8, 2) DEFAULT '0'::numeric,
	"fmaxdes4" numeric(8, 2) DEFAULT '0'::numeric,
	"fmindes1" numeric(8, 2) DEFAULT '0'::numeric,
	"fmindes2" numeric(8, 2) DEFAULT '0'::numeric,
	"fmindes3" numeric(8, 2) DEFAULT '0'::numeric,
	"fmindes4" numeric(8, 2) DEFAULT '0'::numeric,
	"fmaxcamb1" numeric(8, 2) DEFAULT '0'::numeric,
	"fmaxcamb2" numeric(8, 2) DEFAULT '0'::numeric,
	"fmaxcamb3" numeric(8, 2) DEFAULT '0'::numeric,
	"fmaxcamb4" numeric(8, 2) DEFAULT '0'::numeric,
	"fmincamb1" numeric(8, 2) DEFAULT '0'::numeric,
	"fmincamb2" numeric(8, 2) DEFAULT '0'::numeric,
	"fmincamb3" numeric(8, 2) DEFAULT '0'::numeric,
	"fmincamb4" numeric(8, 2) DEFAULT '0'::numeric,
	"fmaxenc1" numeric(8, 2) DEFAULT '0'::numeric,
	"fmaxenc2" numeric(8, 2) DEFAULT '0'::numeric,
	"fmaxenc3" numeric(8, 2) DEFAULT '0'::numeric,
	"fmaxenc4" numeric(8, 2) DEFAULT '0'::numeric,
	"fminenc1" numeric(8, 2) DEFAULT '0'::numeric,
	"fminenc2" numeric(8, 2) DEFAULT '0'::numeric,
	"fminenc3" numeric(8, 2) DEFAULT '0'::numeric,
	"fminenc4" numeric(8, 2) DEFAULT '0'::numeric,
	"fmeddes" numeric(8, 2) DEFAULT '0'::numeric,
	"fmedcamb" numeric(8, 2) DEFAULT '0'::numeric,
	"fmedenc" numeric(8, 2) DEFAULT '0'::numeric
);
